name: CI Pipeline

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  php-lint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # TYPO3 v12 generally requires PHP 8.1+
          extensions: mbstring, intl, json, gd, xml, zip # Common extensions, adjust if needed
          tools: composer # If composer validation or scripts were needed later

      - name: Validate PHP syntax (linting)
        run: |
          find . -name "*.php" \
            -not -path "./.git/*" \
            -not -path "./vendor/*" \
            -not -path "./Resources/Public/Storybook/node_modules/*" \
            -not -path "./Resources/Public/Storybook/storybook-static/*" \
            -not -path "./Resources/Public/Storybook/cypress/*" \ # Exclude cypress config/support files if they are PHP
            -exec php -l {} \;
          # The find command will exit with non-zero if php -l finds an error in any file.

  storybook-jest-tests: # Renamed for clarity
    name: Storybook Jest Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Resources/Public/Storybook # Set default working dir for steps in this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or '20', ensure it matches your dev environment
          cache: 'npm'
          cache-dependency-path: Resources/Public/Storybook/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

  storybook-e2e-cypress: # New job for Cypress
    name: Storybook E2E Tests (Cypress)
    runs-on: ubuntu-latest
    # This job depends on the successful completion of storybook-jest-tests,
    # though not strictly necessary as they test different things.
    # Can run in parallel if preferred.
    # needs: storybook-jest-tests
    defaults:
      run:
        working-directory: ./Resources/Public/Storybook
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Resources/Public/Storybook/package-lock.json

      - name: Install dependencies (including Cypress)
        run: npm ci

      # Grant execute permission for Cypress binary if needed (sometimes required on CI)
      # - name: Grant Cypress execute permission
      #   run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests against static Storybook build
        run: npm run test:e2e:ci
        # This script (test:e2e:ci) handles:
        # 1. Building Storybook to a static directory (storybook:build-static)
        # 2. Serving this static directory (serve-static)
        # 3. Running Cypress tests against the served instance (cy:run)
        # start-server-and-test ensures server is up before tests run and shuts down after.

      - name: Upload Cypress artifacts (screenshots/videos on failure)
        uses: actions/upload-artifact@v3
        if: failure() # Only upload if tests failed
        with:
          name: cypress-artifacts
          path: |
            Resources/Public/Storybook/cypress/screenshots
            Resources/Public/Storybook/cypress/videos
            # Videos are disabled in cypress.config.js, but path kept if re-enabled
